name: Update Files on Release

on:
  push:
    branches:
      - master

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update sep.json
        run: |
          echo "Updating sep.json version"
          version=$(jq -r '.version' sep.json)
          new_version=$(echo $version | awk -F. -v OFS=. '{$NF++;print}')
          jq --arg new_version "$new_version" '.version = $new_version' sep.json > temp.json && mv temp.json sep.json
          jq --arg new_date "$(date +%d.%m.%Y)" '.date = $new_date' sep.json > temp.json && mv temp.json sep.json
          echo $new_version > version.txt

      - name: Update release notes
        run: |
          echo "Appending to release_notes.txt"
          new_version=$(cat version.txt)
          echo "Release version $new_version on $(date +%d.%m.%Y)" >> release_notes.txt

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "$GIT_EMAIL"
          git add sep.json release_notes.txt
          new_version=$(cat version.txt)
          git commit -m "Update sep.json and release_notes.txt to version $new_version" || { echo "No changes to commit"; exit 0; }
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/androkc/joint.git || { echo "Git push failed"; exit 1; }

#      - name: Update other repositories
#        env:
#          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
#          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
#        run: |
#          REPOS=("repo1" "repo2" "repo3") # Укажите здесь ваши репозитории
#          for REPO in "${REPOS[@]}"; do
#            git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/your-org/$REPO.git;
#            cp sep.json $REPO/;
#            cp release_notes.txt $REPO/;
#            cd $REPO;
#            git add .;
#            git commit -m "Update files from release branch to version $new_version";
#            git push https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/your-org/$REPO.git;
#            cd ..;
#          done




