name: Update Files on Release


on:
  push:
    branches:
      - master

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update sep.json
        run: |
          echo "Updating sep.json version"
          jq --arg new_date "$(date +%d.%m.%Y)" '.date = $new_date' sep.json > temp.json && mv temp.json sep.json
          
          # Получаем текущую дату в формате YYYYMMDD
          current_date=$(date +%Y%m%d)

          # Получаем текущую версию из sep.json
          current_version=$(jq -r '.version' sep.json)

          # Разбиваем текущую версию на основную часть и часть сборки
          main_version=$(echo $current_version | awk -F. '{print $1}')
          last_build_date=$(echo $current_version | awk -F. '{print substr($2, 1, 8)}')
          last_build_number=$(echo $current_version | awk -F. '{print substr($2, 9)}')

          echo "Текущая версия: $current_version"
          echo "Ласт дата: $last_build_date"
          echo "Ластовый номер билда: $last_build_number"

          # Если дата изменилась, сбрасываем номер сборки, иначе увеличиваем на 1
          if [ "$current_date" != "$last_build_date" ]; then
            new_build_number="01"
          else
            new_build_number=$(printf "%0${#last_build_number}d" $((10#$last_build_number + 1)))
          fi

          echo "New build number: $new_build_number"

          # Создаем новую версию
          new_version="${main_version}.${current_date}${new_build_number}"
          echo "New version: $new_version"

          # Обновляем версию в sep.json
          jq --arg new_version "$new_version" '.version = $new_version' sep.json > temp.json && mv temp.json sep.json

          # Сохраняем новую версию в файл для дальнейшего использования
          echo $new_version > version.txt

      - name: Check for changes
        run: |
          git add sep.json release_notes.txt
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"; 
            exit 0; 
          fi    

      - name: Update release notes
        run: |
          # Получение сообщения последнего коммита
          commit_message=$(git log -1 --pretty=%B)

          # Определение следующего номера записи
          if [[ -f release_notes.txt ]]; then
            # Извлечение всех номеров записей и определение следующего
            last_number=$(grep -o '^[0-9]\+' release_notes.txt | sort -n | tail -n 1)
            if [[ -z "$last_number" ]]; then
              next_number=1
            else
              next_number=$((last_number + 1))
            fi
          else
            next_number=1
          fi

          # Формирование новой записи
          new_entry="$next_number. $commit_message"

          # Создание временного файла с обновленными записями
          temp_file=$(mktemp)

          # Добавление новой записи в файл
          if [[ -f release_notes.txt ]]; then
            # Копируем существующие записи в новый файл
            cat release_notes.txt > "$temp_file"
          fi

          # Записываем новую запись
          echo "$new_entry" >> "$temp_file"

          # Перемещаем временный файл обратно в основной файл
          mv "$temp_file" release_notes.txt
      

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          set -x
          git config --global user.name "Petr Gurin"
          git config --global user.email "$GIT_EMAIL"
          git add sep.json release_notes.txt
          new_version=$(cat version.txt)
          git commit -m "Update sep.json and release_notes.txt to version $new_version" || { echo "No changes to commit"; exit 0; }
          echo "Token: $PAT_TOKEN"
          echo "Email: $GIT_EMAIL"
          echo "Attempting to push changes..."
          git push https://x-access-token:$PAT_TOKEN@github.com/androkc/joint.git || { echo "Git push failed"; exit 1; }
          echo "Git push succeeded"



