name: Update Files on Release


on:
  push:
    branches:
      - master

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update sep.json
        run: |
          echo "Updating sep.json version"
          jq --arg new_date "$(date +%d.%m.%Y)" '.date = $new_date' sep.json > temp.json && mv temp.json sep.json
          
          # Извлекаем текущую версию
          current_version=$(jq -r '.version' sep.json)
  
          # Разбиваем текущую версию на основную и минорную части
          main_version=$(echo $current_version | awk -F. '{print $1}')
          minor_version=$(echo $current_version | awk -F. '{print $2}')

          echo "Текущая версия: $current_version"
          echo "Минорная версия: $minor_version"

          # Увеличиваем минорную версию на 1
          new_minor_version=$(printf "%0${#minor_version}d" $((10#$minor_version + 1)))
  
          # Создаем новую версию
          new_version="${main_version}.${new_minor_version}"
          echo "Новая версия: $new_version"

          # Обновляем версию в sep.json
          jq --arg new_version "$new_version" '.version = $new_version' sep.json > temp.json && mv temp.json sep.json
  
          # Сохраняем новую версию в файл для дальнейшего использования
          echo $new_version > version.txt
  
          # Обновляем версию последнего элемента массива microservices
          current_rep_version=$(jq -r '.microservices[3].version' sep.json)
          rep_main_version=$(echo $current_rep_version | awk -F. '{print $1}')
          rep_minor_version=$(echo $current_rep_version | awk -F. '{print $2}')
          rep_patch_version=$(echo $current_rep_version | awk -F. '{print $3}')
  
          # Увеличиваем минорную версию микросервиса на 1
          new_rep_minor_version=$(printf "%0${#rep_minor_version}d" $((10#$rep_minor_version + 1)))
  
          # Создаем новую версию для микросервиса
          new_rep_version="${rep_main_version}.${new_rep_minor_version}.${rep_patch_version}"
  
          # Обновляем версию последнего элемента массива в JSON
          jq --arg new_rep_version "$new_rep_version" '.microservices[3].version = $new_rep_version' sep.json > temp.json && mv temp.json sep.json

          # Выводим новую версию последнего микросервиса
          echo "Обновленная версия последнего микросервиса: $new_rep_version"
      

      - name: Update release notes
        run: |
          # Получение сообщения последнего коммита
               commit_message=$(git log -1 --pretty=%B)

          # Фильтрация ненужных строк (например, Merge, pull request, Rebase и т.д.)
               filtered_message=$(echo "$commit_message" | sed '/^\(Merge\|Rebase\|.*pull request.*\|.*from.*\)$/d')

          # Если после фильтрации сообщение пустое, пропускаем его
               if [[ -z "$filtered_message" ]]; then
               echo "Filtered commit message is empty, skipping."
               exit 0
               fi

          # Удаление лишних переносов строк, чтобы всё сообщение оставалось на одной строке
               filtered_message=$(echo "$filtered_message" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g')

          # Определение следующего номера записи
               if [[ -f release_notes.txt ]]; then
          # Извлечение всех номеров записей и определение следующего
               last_number=$(grep -o '^[0-9]\+' release_notes.txt | sort -n | tail -n 1)
               if [[ -z "$last_number" ]]; then
               next_number=1
               else
               next_number=$((last_number + 1))
               fi
               else
               next_number=1
               fi

          # Формирование новой записи
               new_entry="$next_number. $filtered_message"

          # Проверка, заканчивается ли файл на новую строку, и добавление новой строки при необходимости
               if [ -s release_notes.txt ] && [ "$(tail -c1 release_notes.txt)" != "" ]; then
               echo "" >> release_notes.txt
               fi

          # Добавление новой записи
               echo "$new_entry" >> release_notes.txt

      

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          set -x
          git config --global user.name "Petr Gurin"
          git config --global user.email "$GIT_EMAIL"
          git add sep.json release_notes.txt
          new_version=$(cat version.txt)
          git commit -m "Update sep.json and release_notes.txt to version $new_version" || { echo "No changes to commit"; exit 0; }
          
          echo "Token: $PAT_TOKEN"
          echo "Email: $GIT_EMAIL"
          echo "Attempting to push changes..."
          git push https://x-access-token:$PAT_TOKEN@github.com/androkc/joint.git || { echo "Git push failed"; exit 1; }
          echo "Git push succeeded"





      - name: Update other repositories
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          REPO_LIST_SECRET: ${{ secrets.REPO_LIST_SECRET }}
        run: |
          
          IFS=' ' read -r -a repos <<< "$REPO_LIST_SECRET"

          for repo in "${repos[@]}"; do
            git clone https://x-access-token:$PAT_TOKEN@$(echo $repo | sed 's/https:\/\///') temp_repo
            cd temp_repo

            
            git checkout dev || git checkout -b dev

            
            cp ../sep.json sep.json
            cp ../release_notes.txt release_notes.txt

            git add sep.json release_notes.txt
            git config --global user.name "Petr Gurin"
            git config --global user.email "$GIT_EMAIL"
            git commit -m "Update sep.json and release_notes.txt to version $new_version" || { echo "No changes to commit"; cd ..; rm -rf temp_repo; continue; }
           
            git push https://x-access-token:$PAT_TOKEN@$(echo $repo | sed 's/https:\/\///') dev

            cd ..
            rm -rf temp_repo
          done



      - name: Build Docker image
        run: |
          docker build -t test-archive .

      - name: Create and save Docker image archive
        run: |
          mkdir -p image
          docker save test-archive | gzip > image/test-archive.tar.gz

      - name: Commit and push archive
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "androkc"
          git config --global user.email "androkc@github.com"
          git add image/test-archive.tar.gz
          git commit -m "Add Docker image archive"
          # Делаем pull с автоматическим мерджем изменений
          git pull --rebase
          git push
